"use client";
import * as React from "react";
import Link from "next/link";
import { Send, Check } from "lucide-react";
import { useAuth } from "@/components/auth/auth-provider";
import { AccountForm } from "@/components/auth/account-form";
export default function OnboardingPage() {
 const {user,isLoading}=useAuth();const [mode,setMode]=React.useState<"register"|"login">("login");
 return <div className="onboarding"><section className="onboarding-form"><Link href="/" className="brand">KW<span>Kudi Guide</span></Link><div className="onboarding-copy account-onboarding"><span className="eyebrow">EVERY NAIRA, ACCOUNTED FOR.</span><h1>{mode==="login"?"Welcome back.":"A little more clarity."}</h1><p>{mode==="login"?"Log in to pick up where you left off.":"Create your account. Then connect Telegram whenever you’re ready."}</p>{isLoading?<p role="status">Loading your account…</p>:user?<Link className="button black" href="/dashboard">Continue to dashboard →</Link>:<><div className="auth-tabs"><button className={mode==="login"?"selected":""} onClick={()=>setMode("login")}>Log in</button><button className={mode==="register"?"selected":""} onClick={()=>setMode("register")}>Create account</button></div><AccountForm key={mode} mode={mode}/></>}</div></section><aside className="onboarding-art"><span className="eyebrow">LESS GUESSWORK. MORE LIVING.</span><h2>Big picture.<br/>Little effort.</h2><div className="sample-message"><div className="telegram-icon"><Send size={23}/></div><div><strong>You → KudiPal</strong><p>Spent ₦8,500 at Terra Kulture</p><small>Just now <Check size={13}/></small></div></div><div className="sample-receipt"><span className="status-pill active"><Check size={13}/> TRANSACTION TRACKED</span><div className="receipt-heading"><span className="merchant-avatar">TK</span><div><strong>Terra Kulture</strong><p>Food & dining</p></div></div><div className="serif">−₦8,500</div><div className="receipt-foot">A little more clarity.<span>✓</span></div></div><p className="art-caption">From a quick message<br/>to a little peace of mind.</p><small>Illustrative example</small></aside></div>;
}
